Repository chingu-voyages/v41-geckos-team-08, pull requests merged in 2022-10, with the labels that each got.

#15 Documentation: Added Meeting Minutes for Sprint 1
  Documentation/Meetings/Meeting - Sprint #1 - Voyage Kickoff.pdf
Labels: documentation

#61 Andres/feature location
  Server/db_creation.sql
  Server/server.js
  Server/src/documentation/swagger.json
  Server/src/load/countries.js
  Server/src/load/load.js
  Server/src/routes/location.js
Labels: task

#64 Andres/feature users
  Server/server.js
  Server/src/components/format.js
  Server/src/components/saveCities.js
  Server/src/components/saveTrades.js
  Server/src/middleware/validateEmail.js
  Server/src/middleware/validateUUID.js
  Server/src/routes/users.js
Labels: task

#68 Andres/Feature-Trades
  Server/db_creation.sql
  Server/src/components/saveTrades.js
  Server/src/routes/trades.js
  Server/src/routes/users.js
Labels: task, must_have

#84 Andres/Jobs-Route
  Server/package.json
  Server/src/components/format.js
  Server/src/middleware/validateUUID.js
  Server/src/routes/jobs.js
  Server/tests/common/create-trade.js
  Server/tests/routes/jobs.test.js
Labels: task, should_have

#86 added authorization
  Server/src/auth/login.js
  Server/src/middleware/authorization.js
  Server/src/middleware/jwtGenenrator.js
  Server/src/routes/jobs.js
  Server/src/routes/trades.js
Labels: task, should_have
